### ISSUE TITLE
3i Cercopidae sector did not merge properly on  2024-11-08 X-Release

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#816]
**Describe the problem**:

3i Cercopidae sector [did not merge](https://www.checklistbank.org/dataset/305087/names?SECTOR_DATASET_KEY=2317&TAXON_ID=6239Q&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&sectorMode=merge&sortBy=taxonomic) on   2024-11-08 X-Release

<img width="933" alt="Captura de pantalla 2024-11-14 a la(s) 3 42 00 p m" src="https://github.com/user-attachments/assets/2945c2d3-5363-42d9-8d35-82c1f9ca743e">

 Logs, show no new added names but apparently some names where updated, never the less this source should provide several new names, for example  [Cephisus diminutus](https://www.checklistbank.org/dataset/305087/nameusage/KB7BF) should had been added [from this sector](https://www.checklistbank.org/dataset/2317/taxon/2053) an not from plazi

```
21832133:2024-11-09 14:03:58,257 INFO  XRelease                         Merge Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}. #69 out of 53944
21832134:2024-11-09 14:03:58,321 INFO  SectorSync                       Syncing sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]} into release 305087
21832135:2024-11-09 14:03:58,322 INFO  SectorRunnable              2317 Start SectorSync for sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}
21832136:2024-11-09 14:03:58,532 INFO  SectorRunnable              2317 Loaded 7222 editorial decisions for sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}
21832137:2024-11-09 14:03:58,545 INFO  SectorRunnable              2317 Loaded 0 sectors incl 0 merge sectors targeting taxa from sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}
21832138:2024-11-09 14:03:58,561 INFO  SectorSync                  2317 Loaded 0 children from other sectors with a parent from sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}
21832139-2024-11-09 14:03:58,568 INFO  SectorSync                  2317 Loaded 1 sector subjects for auto blocking

21832148-2024-11-09 14:03:58,631 INFO  SectorSync                  2317 MERGE taxon tree ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035] to SUPERFAMILY Cercopoidea [b5feLsEySYQ-3pDCJlucj1]. Blocking 3532 nodes
21832149:2024-11-09 14:03:58,713 INFO  SectorSync                  2317 Synced null taxa and null synonyms from sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}
21832150:2024-11-09 14:03:58,713 INFO  SectorSync                  2317 Sync name & taxon relations from sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}
21832151-2024-11-09 14:03:58,713 INFO  UsageMatcherGlobal          2317 Remove usage loader for dataset 305087
21832152:2024-11-09 14:03:58,713 INFO  TreeMergeHandler            2317 Sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}: Total processed=0, thrown=0, ignored=0, created=0, updated=0
21832153-2024-11-09 14:03:58,715 INFO  TreeBaseHandler             2317 Include entities: SPECIES_INTERACTION, REFERENCE, TYPE_MATERIAL, NAME_USAGE, VERNACULAR, DISTRIBUTION, NAME_RELATION

21832293-2024-11-09 14:04:03,851 DEBUG TreeMergeHandler            2317 Updated Oliarus orono Kirkaldy, 1902 [SPECIES] {X__tN4vFsgNn2hIz30X0k} with publishedIn
21832294:2024-11-09 14:04:03,879 INFO  SectorSync                  2317 Updated 132 names from sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}
21832295-2024-11-09 14:04:03,879 INFO  UsageMatcherGlobal          2317 Remove usage loader for dataset 305087
21832296:2024-11-09 14:04:03,880 INFO  TreeMergeHandler            2317 Sector Sector{56376, datasetKey=3, mode=MERGE, `subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}: Total processed=0, thrown=0, ignored=0, created=0, updated=132`
21832297:2024-11-09 14:04:03,880 INFO  SectorRunnable              2317 Build metrics for sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}
21832298-2024-11-09 14:04:04,041 INFO  FileMetricsDao              2317 Written 0 name strings for dataset 3:56376-3
21832299:2024-11-09 14:04:04,042 INFO  SectorRunnable              2317 Update search index for sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}
21832300:2024-11-09 14:04:04,042 DEBUG SectorSync                  2317 Will index merge sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]} at the end of the release. Skip immediate indexing
21832301:2024-11-09 14:04:04,042 INFO  SectorRunnable              2317 Completed SectorSync for sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]} with 0 names and 0 usages
21832302-2024-11-09 14:04:04,046 INFO  SectorRunnable              2317 SectorSync took 00:00:06

54319385-2024-11-10 10:44:33,624 INFO  FileMetricsDao                   Written 116 name strings for dataset 305087:2243-28
54319386:2024-11-10 10:44:33,626 INFO  XRelease                         Build metrics for sector Sector{56376, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Cercopoidea Leach, 1815 [321 parent=1036035]}
54319387-2024-11-10 10:44:33,736 INFO  FileMetricsDao                   Written 0 name strings for dataset 305087:56376-3
(bas



In contrast Fulgoroidea 3i sector [did merge](https://www.checklistbank.org/dataset/305087/names?SECTOR_DATASET_KEY=2317&TAXON_ID=FL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&sectorMode=merge&sortBy=taxonomic):


<img width="792" alt="Captura de pantalla 2024-11-14 a la(s) 3 50 00 p m" src="https://github.com/user-attachments/assets/dad96895-f450-4c9b-93dd-b5ab5f3aee59">


The logs of Fulgoroidea sector, it states that several names where created but at the ed reports a sync error (not sure whta it meas as the sector clearly was created)

21752372:2024-11-09 13:59:03,937 INFO  XRelease                         Merge Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]}. #68 out of 53944
21752373:2024-11-09 13:59:03,981 INFO  SectorSync                       Syncing sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]} into release 305087
21752374:2024-11-09 13:59:03,981 INFO  SectorRunnable              2317 Start SectorSync for sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]}
21752375:2024-11-09 13:59:04,296 INFO  SectorRunnable              2317 Loaded 7222 editorial decisions for sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]}
21752376:2024-11-09 13:59:04,310 INFO  SectorRunnable              2317 Loaded 0 sectors incl 0 merge sectors targeting taxa from sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]}
21752377:2024-11-09 13:59:04,327 INFO  SectorSync                  2317 Loaded 0 children from other sectors with a parent from sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]}
21752378-2024-11-09 13:59:04,335 INFO  SectorSync                  2317 Loaded 1 sector subjects for auto blocking

21832095-2024-11-09 14:03:58,226 DEBUG TreeMergeHandler            2317 Updated Bebaiotes pulla Muir, 1934 [SPECIES] {vZ4wQj-d7XthECDUX6l170} with publishedIn
21832096:2024-11-09 14:03:58,229 ERROR SectorSync                  2317 Sync has thrown an exception. Abort sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]}
21832097-2024-11-09 14:03:58,229 INFO  UsageMatcherGlobal          2317 Remove usage loader for dataset 305087
`21832098:2024-11-09 14:03:58,230 INFO  TreeMergeHandler            2317 Sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]}: Total processed=21956, thrown=145, ignored=1313, created=4635, updated=12346`
21832099:2024-11-09 14:03:58,247 ERROR SectorRunnable              2317 Failed SectorSync{sectorKey=Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]}, subjectDatasetKey=2317, sector=Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]}, created=2024-11-09T13:59:03.950288 by 728}
21832100:java.lang.IllegalStateException: Sync of sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]} has thrown an exception
21832101-	at life.catalogue.assembly.SectorSync.processTree(SectorSync.java:334)

21832114-	at java.base/java.lang.Thread.run(Thread.java:834)
21832115:2024-11-09 14:03:58,249 ERROR SyncFactory                 2317 Sector merge Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]} into release 305087 failed: Sync of sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]} has thrown an exception
21832116:java.lang.IllegalStateException: Sync of sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]} has thrown an exception
21832117-	at life.catalogue.assembly.SectorSync.processTree(SectorSync.java:334)

21832131-2024-11-09 14:03:58,256 INFO  SectorRunnable              2317 SectorSync took 00:04:55
`21832132:2024-11-09 14:03:58,256 ERROR XRelease                         Failed to sync Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]} with error: IllegalStateException: Sync of sector Sector{56225, datasetKey=3, mode=MERGE, subjectDatasetKey=2317, subject=ACCEPTED SUPERFAMILY Fulgoroidea Latreille, 1807 [56053 parent=56032]} has thrown an exception`
```

**Comment by mdoering** [comment]
The sync history indeed shows zero taxa being merged, just 106 references:
https://www.checklistbank.org/catalogue/3/sector/sync?sectorKey=56376

Remember that all decisions created in the base release for the source will also apply to merges.
There are 2.317 block decisions by Yuri, maybe he blocked some higher taxa of the tree? E.g. infraorder Fulgoromorpha is blocked and also superfamily _Cercopoidea_, both of which are the merge sectors.

I am unclear what best to do. I do think we want the base decisions to remain also in the XR, otherwise we add back in all the crap that was sorted out. But we could add a flag `ignoreInMerge` to all decisions that prevents them from being applied during merge syncs. Maybe there is a simpler way to do this...

**Comment by camiplata** [comment]
yes ,we do want to keep the base decisions, this is also key for ITIS wich we use for both the base and extended release.

There are not many cases like the one of 3i so maybe the ignoreInMerge flag could work, or a setting on the merge sector that ignores base decisions for that specific merge sector. Nevertheless the decisions are rather made on the data source not on the sector so that's problematic.

**Comment by mdoering** [comment]
How about adding a decision override section to the XR configs? Sth like

```
decisions:
  2317:
    - mode: reviewed
       subject: 
           name: Cercopoidea
           rank: superfamily
```

Then these decisions will override existing ones or be added if none exist. And `mode=reviewed` means all good, include.

**Comment by camiplata** [comment]
I like this approach, so we can quickly address the problem. And we also avoid changing Yury's workflow.

 mode=reviewed "means all good, include".. the subject in the assembly?

**Comment by camiplata** [comment]
on it

**Comment by mdoering** [comment]
a `subject` can have any of these properties, but must at least always have a `name`:

```
subject:
  name: Abies alba
  authorship: Mill.
  rank: species
  status: accepted
  parent: Abies
```

The more properties are given the stricter the matching is to filter out unwanted names, e.g. when the source contains duplicates with the same name, rank & authorship, but maybe places them under a different direct parent. That is the same behavior as regular decisions.

**Comment by camiplata** [comment]
<img width="661" alt="Captura de pantalla 2024-11-15 a la(s) 11 48 53 a m" src="https://github.com/user-attachments/assets/db50f6f3-9c2a-489f-9f0d-b8a04c067c9f">

**Comment by mdoering** [comment]
there are some YAML syntax problems, best to verify the content always with https://www.yamllint.com

In this case it should be:

```
decisions:
  2317:
    - mode: reviewed
      subject: 
           name: Cercopoidea
           rank: superfamily

    - mode: reviewed
      subject: 
           name: Fulgoromorpha
           rank: infraorder
```

**Comment by camiplata** [comment]
fixed, thanks for the url

**Comment by camiplata** [comment]
The addition did not make a difference:

https://www.checklistbank.org/dataset/305209/taxon/8JR4J  comes from PaleoDB while it should had come from 3i https://www.checklistbank.org/dataset/2317/taxon/48669,

**Comment by mdoering** [comment]
The change was not deployed to prod then!
The version used by the last XR was build on [2024-11-14 12:42](https://repository.gbif.org/repository/snapshots/org/catalogueoflife/webservice/1.0-SNAPSHOT/webservice-1.0-20241114.124208-1261.jar)

The config change above was added only on the 15th and deployed to prod on the 18th.
Let's wait for next week
